//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTwitchTTS.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTwitchTTS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Р—РЅР°С‡РёС‚ Р°РЅРµРєРґРѕС‚: РїСЂРёС€РµР» РјСѓР¶РёРє РІ С†РёСЂРє Рё РіРѕРІРѕСЂРёС‚: С…РѕС‡Сѓ СЃС‚Р°С‚СЊ РєР»РѕСѓРЅРѕРј. РќСѓ, РєР»РѕСѓРЅС‹ РµРіРѕ СЃРїСЂР°С€РёРІР°СЋС‚: СЂР°Р· С…РѕС‡РµС€СЊ, РјС‹ С‚РµР±Рµ Р°РЅС€Р»Р°Рі РґР°РґРёРј.
        ///Рђ РѕРЅ РіРѕРІРѕСЂРёС‚, РЅРµ С…РѕС‡Сѓ Р°РЅС€Р»Р°Рі. РљР»РѕСѓРЅС‹ РіРѕРІРѕСЂСЏС‚: Р° С‡РµРіРѕ С‚РѕРіРґР° С…РѕС‡РµС€СЊ? Рђ РѕРЅ РіРѕРІРѕСЂРёС‚: РЅСѓвЂ¦ С…РѕС‡Сѓ, РіРѕРІРѕСЂРёС‚, С‡С‚РѕР± РІСЃРµ РЅР° РјРµРЅСЏ СЃРјРѕС‚СЂРµР»Рё.
        ///Р СЃРјРѕС‚СЂСЏС‚. РќРѕ РЅРµ РєР°Рє РЅР° РєР»РѕСѓРЅР°, Р°  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string neyroaneki {
            get {
                return ResourceManager.GetString("neyroaneki", resourceCulture);
            }
        }
    }
}
